// This file is auto-generated by Convex
// During development, this is a placeholder that will be replaced
// when you deploy to Convex

import { anyApi } from 'convex/server'

export const api = anyApi as any
